guardian/scala-steward-public-repos

- .github/workflows/scala-steward.yml
Following on from #3 , [I realised the default config wasn't being found](https://github.com/scala-steward-org/scala-steward-action/issues/353#issuecomment-1185614639) - but that's because we weren't checking out the repository!
https://github.com/scala-steward-org/scala-steward-action/issues/353#issuecomment-1185638287
> Checkout repo so we can access default config

- REPOSITORIES.md
Following on from:
- https://github.com/guardian/amiable/pull/182
- https://github.com/guardian/.github/pull/23
Causes PRs to be opened on the non default branch [`dependency-updates`](https://github.com/guardian/amiable/pull/182/files#diff-05836425388f26ba06446b5c1272d551ace0f8f0e51fef3f41cec358e243d0f1R6) intended to then follow the [dependency update process](https://github.com/guardian/.github/pull/23/files#diff-9878c091051bb15a98b39f1494423c81bf09dafea3740080054300552c1454d6R1).
> Adds guardian/amiable to list of repositories

- scala-steward.conf
Reduces the default frequency of PRs opened by Scala Steward for AWS SDK v1 changes to weekly (they seem to release every week day, but these changes aren't likely to ever be useful to treat separately). Unfortunately the group ID `com.amazonaws` includes non-java-SDK libraries which makes it impossible to treat these separately in scala stewards config. Our compromise is to use 7 day frequency, so that changes to non-SDK libraries are still relatively timely.
co-authored-by: @jacobwinch
> Reduce default frequency of v1 AWS SDK  updates

- REPOSITORIES.md
Adds Janus-app (the public app) and Prism to the list of repositories to be updated by Scala Steward.
> Add Prism and Janus-app to repositories

- scala-steward.conf
I noticed that our recently added rule for the `com.amazonaws` group was not restricting pull requests to every 7 days - we were still receiving them almost daily e.g. https://github.com/guardian/amiable/pulls?q=is%3Apr+is%3Aclosed+aws-java. Another piece of [evidence](https://github.com/guardian/ophan/pulls?q=is%3Apr+is%3Aclosed+software.amazon.awssdk) from Ophan: pull requests for the v2 SDK are every 7 days there, instead of 30 (it's only 7 days because they have a global setting for that.) On closer inspection it seems we're missing the pluralisation of the time span we use in the config file, so this PR fixes them.
Hard to test, but not that risky to merge and observe.
> Fix pull request frequency definitions

- .github/dependabot.yml
This should help to know when Github actions need to be updated.
See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> Keep GHA versions up to date

- REPOSITORIES.md
Adds [ssm-scala](https://github.com/guardian/ssm-scala) to monitored repos. This is a @guardian/devx-security repo and we should be on top of updates.
The application has been added to the repo already as [per the instructions](https://github.com/guardian/scala-steward-public-repos/blob/main/README.md).
> Add ssm-scala to monitored projects

- REPOSITORIES.md
Now that pull request [grouping](https://github.com/guardian/scala-steward-public-repos/pull/40) has been introduced we don't need the workflows associated with a `dependency-updates` branch to help reduce noise.
When we've merged this change, let's check we're happy with the automated PRs being raised by scala-steward, after which we can then safely delete the dependency-updates [workflows](https://github.com/guardian/mobile-n10n/tree/main/.github/workflows) from the n10n repo.
> Raise dependency updates for n10n against main branch

- REPOSITORIES.md
https://github.com/guardian/scala-steward-public-repos/actions/runs/5091072018/jobs/9150648602
```
2023-05-26 13:16:37,520 ERROR Steward guardian/zuora-creditor failed
org.scalasteward.core.forge.github.GitHubException$RepositoryArchived: guardian/zuora-creditor
```
Repository archived with https://github.com/guardian/zuora-creditor/pull/193 - when we archive a repo, we need to remove it from https://github.com/guardian/scala-steward-public-repos/blob/main/REPOSITORIES.md !
cc @gnm-notona & @shtukas
> Remove `guardian/zuora-creditor` - archived, causing errors

- .github/workflows/reusable-scala-steward.yml
This includes https://github.com/scala-steward-org/scala-steward-action/pull/502, for a more friendly summary of which repos failed or succeeded as Scala Steward was processing them.
> Update to latest Scala Steward Action with new Job Summary

- running-locally.md
These instructions explain how to run the Scala Steward code locally with [Java Remote debugging](https://www.jetbrains.com/help/idea/debugging-code.html) enabled, while keeping the configuration as close as possible to how Scala Steward is launched in the GitHub Action. 
This has been useful for looking into why Scala Steward was ignoring our `pullRequests.frequency` configuration!
https://github.com/guardian/scala-steward-public-repos/assets/52038/0c7cb2f6-9d9b-4615-b56c-301db9b5081c
> Add docs on how run & debug Scala Steward locally

- scala-steward.conf
Akka have moved to a commercial licence for 2.7+, which we want to avoid. This is a temporary solution to help teams avoid upgrading to a commercial version accidentally.
Medium term, we are hoping that Snyk will fix their licence check for Akka. We can then rely on that instead.
For a fuller discussion, see https://github.com/guardian/scala-steward-public-repos/issues/53.
> Ignore Akka dependencies

- .github/workflows/reusable-scala-steward.yml
- scala-steward.conf
* Adds `dependencies` label to Scala Steward PRs.
* update PR titles to be semantic and match Dependabot
The labels are helpful to identify bot updates and combine them into a single PR (across Dependabot and Scala Steward).
Run.
> Add labels

- scala-steward.conf
This will avoid repos updating to non-LTS versions by default.
Individual repos can always overrule it if required.
> Ignore non-LTS versions of Scala 3 library

- .github/workflows/reusable-scala-steward.yml
See https://github.com/guardian/scala-steward-public-repos/pull/67#issuecomment-1997972775 - this does fix the setup-java config, which is good - but as @johnduffell predicted, we do have a project that can't handle Java 21 yet:
https://github.com/guardian/scala-steward-public-repos/actions/runs/8285120256/job/22672145296#step:6:2622
Looks like just one project though: [`guardian/mobile-save-for-later`](https://github.com/guardian/mobile-save-for-later)
> Try to fix setup-java action - remove sbt caching

- scala-steward.conf
Adds Twitter Scrooge to the `updates.ignore` list.
Scrooge has updated their forbidden keywords to be the same as Apache Thrift: https://github.com/twitter/scrooge/commit/884f360361bc4abf2e2c91ada1e9cbc15f584b0d. CAPI uses the word `end` which is a reserved keyword, so any Scrooge upgrade above [`22.2.0`](https://github.com/twitter/scrooge/releases/tag/scrooge-22.2.0) will fail until we rename this field. See also: https://trello.com/c/1rp2MVVA and https://github.com/guardian/content-api/issues/2903. By ignoring these dependencies we're unblocking Scala Steward to raise PRs with other upgrades.
> Ignore Twitter Scrooge updates

- README.md
See https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow#configuring-a-workflow-to-run-manually
> Note that need write access to run the workflow manually

- .github/workflows/reusable-scala-steward.yml
See also https://github.com/guardian/janus/pull/4385 
More at https://eed3si9n.com/setup-sbt/
https://github.com/guardian/scala-steward-public-repos/actions/runs/11345941737
We ran the workflow on this branch and it ran successfully
> Fix failing workflows by making sbt available

- scala-steward.conf
These changes come out of discussions I've had with people on various teams (eg MAPI, DevX, Ophan) across the department - the teams all have different needs, so no perfect single set of defaults exists, but I've done my best to take feedback into account! Happy to discuss further in this PR.
* Add new PR group for Guardian libraries (`com.gu`) - Guardian library updates are generally more important to us, so allow a frequency of **2 days** on these (our original grouping came with https://github.com/guardian/scala-steward-public-repos/pull/40)
* Slow down AWS SDK v1 dependency PRs from weekly to the same cadence as AWS SDK v2 - **once per month**. Note that projects _should_ be  https://github.com/guardian/maintaining-scala-projects/issues/9, as v1 is in maintenance mode and will soon be …
> Introduce PR group for Guardian libraries, slow cadence on other PRs

- .github/workflows/reusable-scala-steward.yml
> Remove SBT setup step

- scala-steward.conf
@akash1810 on DevX [asked](https://chat.google.com/room/AAAAxU6hmMI/Z5b1diy4PoU/Z5b1diy4PoU?cls=10) if it was possible to tune the labels applied to pull-requests raised by Scala Steward. There are a lot of labels added by Scala Steward - for instance, on this PR Akash pointed to - https://github.com/guardian/riff-raff/pull/1409 :
```
artifact-migrations
commit-count:n:22
dependencies
early-semver-major
early-semver-minor
early-semver-patch
early-semver-pre-release
library-update
old-version-remains
sbt-plugin-update
semver-spec-major
semver-spec-minor
semver-spec-patch
semver-spec-pre-release
test-library-update
version-scheme:early-semver
version-scheme:semver-spec
```
Of all these labels, Akash only found the `dependencies` one useful - I'm not aware of the others being used for …
> Reduce label-noise on generated PRs

- scala-steward.conf
See https://github.com/guardian/content-api-firehose-client/releases/tag/v1.0.26
> Avoid broken content-api-firehose-client release

- scala-steward.conf
We added some config in #63 to ensure that projects didn't inadvertently step out of LTS versions of Scala and into [Scala Next](https://www.scala-lang.org/development/).
However, since scala-steward-org/scala-steward#3328 this is now redundant as Scala Steward has an internal mechanism for staying on either an LTS or a `Next` track.  Any project on an LTS version of Scala will only be bumped to successive LTS versions.  If a project wants to use `Next` versions it just has to be bumped manually to a `Next` version and that will then automatically be kept up to date.
> chore: Remove redundant LTS-handling config

- scala-steward.conf
@vlbee pointed out to me that artifacts like `"software.amazon.kinesis" % "amazon-kinesis-client"` were being included in _"**Non**-AWS dependency updates"_ (like https://github.com/guardian/mobile-notifications-content/pull/150) - and that's incorrect, we would expect that to go into the AWS updates.
It turns out that our _"AWS dependency updates"_ and _"Guardian library updates"_ grouping rules were both failing to match all the group ids we would want (unfortunately, specifying, eg, `com.gu`, does not also match `com.gu.play-googleauth`) - this change updates our global `.scala-steward.conf` to fix this.
* https://github.com/scala-steward-org/scala-steward/issues/3655
* https://github.com/scala-steward-org/scala-steward/pull/3654
> Fix `pullRequests.grouping` config to include sub-group ids
